apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-app-deployment
  labels:
    app: fin-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fin-app
  template:
    metadata:
      labels:
        app: fin-app
    spec:
      containers:
      - name: fin-app
        image: lolaasher/fin-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URL
            value: postgresql://user:password@fin-app-db:5432/finance_db
          
---
apiVersion: v1
kind: Service
metadata:
  name: fin-app-service
spec:
  type: NodePort
  selector:
    app: fin-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
      