version: '3.8'

services:
  # This is our web app
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - web_logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/finance_db
    depends_on:
      - db

  # This is our database
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=finance_db

# These are our "magic memory cards"
volumes:
  postgres_data:
  web_logs: {}